// THIS IS FOR JOB ORDER IN OCCUPATION !

/datum/map/geliak
	allowed_jobs = list(
	/datum/job/governor,
	/datum/job/heir,
	/datum/job/servant,
	/*/datum/job/inquisitor,*/
	/datum/job/ordinate,
	/*/datum/job/acolyte,*/
	/datum/job/royalguard,
	/datum/job/ig/commissar,
	/datum/job/ig/sergeant,
	/datum/job/ig/guardsman/sniper,
	/datum/job/ig/guardsman/sharpshooter,
	/datum/job/ig/medicae,
	/datum/job/villagemedicae,
	/datum/job/ig/guardsman,
	/datum/job/ig/bullgryn,
	/datum/job/ig/whiteshield,
	/*/datum/job/skitarii,*/
	/datum/job/explorer,
	/datum/job/biologis,
	/datum/job/engineer,
	/datum/job/techmenial,
	/datum/job/deacon,
	/datum/job/canoness,
	/datum/job/sistersuperior,
	/datum/job/hospitaller,
	/datum/job/hydro,
	/datum/job/marshal,
	/datum/job/investigator,
	/datum/job/enforcer,
	/datum/job/arbitrator,
	/datum/job/scavenger,
	/datum/job/progena,
	/*/datum/job/roguetrader,*/
	/*/datum/job/xenomerc,*/
	/datum/job/bouncer,
	/datum/job/gangboy,
	/datum/job/pathfinder,
	/datum/job/penitent,
	/datum/job/citizen,
	/datum/job/roguedoc
	)
